package com.example.pembuatqr;

import android.content.DialogInterface;
import android.content.Intent;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.activity.EdgeToEdge;
import androidx.activity.result.ActivityResultLauncher;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.journeyapps.barcodescanner.BarcodeEncoder;
import com.journeyapps.barcodescanner.ScanContract;
import com.journeyapps.barcodescanner.ScanOptions;

public class CreateQr extends AppCompatActivity {
    private EditText etInput;
    private Button btnCreate,btnDownloadQrCode;
    private ImageView ivQrCode;
    private TextView tv1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_buat_qr);

        etInput = findViewById(R.id.etInput);
        btnCreate = findViewById(R.id.btnCreate);
        ivQrCode = findViewById(R.id.ivQrCode);
        tv1 = findViewById(R.id.tv1);
        btnDownloadQrCode = findViewById(R.id.btnDownloadQrCode);



        btnCreate.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                String inputText = etInput.getText().toString().trim();

                if (!inputText.isEmpty()) {
                    // Jika ada teks, sembunyikan TextView dan tampilkan ImageView dengan QR Code
                    tv1.setVisibility(View.GONE);
                    ivQrCode.setVisibility(View.VISIBLE);
                    btnDownloadQrCode.setVisibility(View.VISIBLE);


                    // Buat QR Code
                    MultiFormatWriter writer = new MultiFormatWriter();
                    try {
                        BitMatrix bitMatrix = writer.encode(inputText, BarcodeFormat.QR_CODE, 300, 300);
                        BarcodeEncoder barcodeEncoder = new BarcodeEncoder();
                        Bitmap bitmap = barcodeEncoder.createBitmap(bitMatrix);

                        ivQrCode.setImageBitmap(bitmap);

                    } catch (WriterException e) {
                        throw new RuntimeException(e);
                    }
                } else {
                    // Jika EditText kosong, tampilkan TextView dan sembunyikan ImageView
                    tv1.setText("Masukan teks atau link");
                    tv1.setVisibility(View.VISIBLE);
                    ivQrCode.setVisibility(View.GONE);

                    btnDownloadQrCode.setVisibility(View.GONE);

                }
            }
        });
        btnDownloadQrCode.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                saveQrCodeToGallery();
            }
        });


    }


    //Method Save
    private void saveQrCodeToGallery() {
        // Mendapatkan gambar dari ImageView sebagai Bitmap
        ivQrCode.setDrawingCacheEnabled(true);
        Bitmap bitmap = Bitmap.createBitmap(ivQrCode.getDrawingCache());
        ivQrCode.setDrawingCacheEnabled(false);

        // Simpan gambar ke galeri
        String savedImageURL = MediaStore.Images.Media.insertImage(
                getContentResolver(),
                bitmap,
                "QRCode_" + System.currentTimeMillis(),
                "QR code generated by QR Generator App"
        );

        if (savedImageURL != null) {
            Toast.makeText(this, "QR Code berhasil disimpan ke galeri", Toast.LENGTH_SHORT).show();
        } else {
            Toast.makeText(this, "Gagal menyimpan QR Code", Toast.LENGTH_SHORT).show();
        }
    }


}